WITH A AS (
SELECT ID,PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS SIZEPER
FROM ECOLI_DATA
)

SELECT ID, (CASE
WHEN SIZEPER <= 0.25 THEN 'CRITICAL'
WHEN SIZEPER <= 0.50 THEN 'HIGH'
WHEN SIZEPER <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END ) AS COLONY_NAME
FROM A
ORDER BY ID