WITH RANKING AS (SELECT
           MEMBER_ID, DENSE_RANK() OVER(ORDER BY COUNT(REVIEW_ID) DESC) AS REVIEW_RANK
           FROM REST_REVIEW
           GROUP BY MEMBER_ID)

# SELECT *
# FROM A


SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d")
FROM MEMBER_PROFILE P JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT MEMBER_ID
                    FROM RANKING
                    WHERE REVIEW_RANK = 1)                    
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT