# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자','국','김치','식용유')
# GROUP BY CATEGORY, PRICE
# HAVING (CATEGORY,PRICE) IN (SELECT CATEGORY, MAX(PRICE) AS PRICE
#                             FROM FOOD_PRODUCT
#                             GROUP BY CATEGORY)
# ORDER BY MAX_PRICE DESC


WITH A AS (
        SELECT CATEGORY, PRICE, PRODUCT_NAME,
            RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM A
WHERE RANKING = 1
ORDER BY PRICE DESC;